1:
  connections: [{id: 2, cost: 20.0}]
  floor_id: "1"
  x: 0.0
  y: 0.0

2:
  connections: [{id: 1, cost: 20.0}, {id: 3, cost: 21.0}, {id: 5, cost: 11.0}]
  floor_id: "1"
  x: 1.0
  y: 2.0

3:
  connections: [{id: 2, cost: 21.0}, {id: 4, cost: 1.0}]
  floor_id: "2"
  x: 0.0
  y: 0.0

4:
  connections: [{id: 3, cost: 3.0}]
  floor_id: "2"
  x: 2.0
  y: 1.0

5:
  connections: [{id: 2, cost: 11.0}]
  floor_id: "1"
  x: 3.0
  y: 6.0
