features:
  one:
    xmin: 0.0
    xmax: 0.0
    ymin: 0.0
    ymax: 0.0
    label: "ramp1"
    floor: "1"
  two:
    xmin: 1.0
    xmax: 1.0
    ymin: 1.0
    ymax: 1.0
    label: "ramp2"
    floor: "1"

destinations:
  d1:
    x: 0.0
    y: 0.0
    floor: "3"
    label: "Room 324"
  d2:
    x: 2.0
    y: 2.0
    floor: "1"
    label: "Room 111"
